apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
  ML_SERVICE_URL: "http://{{ .Values.ml.name }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.ml.port }}/predict"
  CACHE_TIMEOUT: "{{ .Values.cache.timeout }}"

