apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: {{ .Values.letsencrypt.clusterIssuerName }}  # Cert-manager annotation
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - {{ .Values.api.domain }}
    secretName: {{ .Values.tls.secretName }}  # Secret to store SSL certificate
  rules:
  - host: {{ .Values.api.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              number: {{ .Values.frontend.port }}

