apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ml.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.ml.port }}
    targetPort: {{ .Values.ml.port }}
  selector:
    app: {{ .Values.ml.name }}

