apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  ML_SERVICE_URL: "http://ml.default.svc.cluster.local:8000/predict"
  CACHE_TIMEOUT: "60"

